# .sops.yaml
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
    - age: []
      # Replace the below with your SSH public keys converted to age.
      # You can convert them using: ssh-to-age -i /path/to/public/key.pub
      # Or just use the ssh key directly if sops supports it (but sops-nix often prefers age)
      # For example:
      # - age: "age1..." # User key (so you can edit)
      # - age: "age1..." # Host key (so the server can decrypt)
